import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { join } from "node:path";

interface KbNode {
  id: string;
  text: string;
  props?: Record<string, unknown>;
  children?: string[];
  createdAt?: string;
  updatedAt?: string;
}

interface KbContext {
  root: string;
  nodes: KbNode[];
  qdb?: unknown;
  store?: unknown;
}

interface PassthroughSchema<T = unknown> {
  parse(val: unknown): T;
}

const passthroughSchema: PassthroughSchema<Record<string, unknown>> = {
  parse(val: unknown): Record<string, unknown> {
    if (val && typeof val === "object" && !Array.isArray(val)) {
      return val as Record<string, unknown>;
    }
    return {};
  }
};

function formatNodeTree(nodes: KbNode[], rootNode: KbNode, indent = ""): string {
  const lines: string[] = [];
  lines.push(`${indent}- ${rootNode.text}`);
  if (rootNode.children && Array.isArray(rootNode.children)) {
    for (const childId of rootNode.children) {
      const child = nodes.find((n) => n.id === childId);
      if (child) {
        lines.push(formatNodeTree(nodes, child, indent + "  "));
      }
    }
  }
  return lines.join("\n");
}

function generateReadme(nodes: KbNode[]): string {
  const contentNodes = nodes.filter(
    (n) => !n.id.startsWith("sys.") && !n.id.startsWith("lens.")
  );

  const childIds = new Set<string>();
  for (const n of contentNodes) {
    if (n.children) {
      for (const c of n.children) childIds.add(c);
    }
  }
  const rootContentNodes = contentNodes.filter((n) => !childIds.has(n.id));

  const items = rootContentNodes
    .map((n) => formatNodeTree(contentNodes, n))
    .join("\n\n");

  return `<!-- generated by kb projection; do not edit directly -->
# Learning Workspace

Repo for learning and experiments.

## Principles & Organization
${items}

## Structure
- Each concept/experiment begins in its own dedicated folder.
- Grouping and hierarchy will evolve as patterns emerge over time.
`;
}

function generateAgentsMd(nodes: KbNode[]): string {
  const contentNodes = nodes.filter(
    (n) => !n.id.startsWith("sys.") && !n.id.startsWith("lens.")
  );

  const childIds = new Set<string>();
  for (const n of contentNodes) {
    if (n.children) {
      for (const c of n.children) childIds.add(c);
    }
  }
  const rootContentNodes = contentNodes.filter((n) => !childIds.has(n.id));

  const outline = rootContentNodes
    .map((n) => formatNodeTree(contentNodes, n))
    .join("\n");

  return `<!-- generated by kb projection; do not edit directly -->
# AGENTS.md

Context and guidelines for AI agents working in this repository.

## Repository Purpose & Rules
- **Learning & Experiments**: This repository is dedicated to learning concepts and running experiments.
- **Starting Simple**: Every concept/experiment starts in its own single directory.
- **Organic Evolution**: Hierarchy and groupings will be introduced only when needed down the line.

## Knowledge Base Summary
${outline}
`;
}

export default [
  {
    id: "all",
    title: "Project KB to Markdown",
    description: "Render KB outliner nodes into README.md and AGENTS.md",
    mode: "apply" as const,
    aliases: ["project.render", "render.all", "project.all"],
    inputSchema: passthroughSchema,
    outputSchema: passthroughSchema,
    async handler(ctx: KbContext, _input: unknown) {
      const readmeContent = generateReadme(ctx.nodes);
      const agentsContent = generateAgentsMd(ctx.nodes);

      const readmePath = join(ctx.root, "README.md");
      const agentsPath = join(ctx.root, "AGENTS.md");

      writeFileSync(readmePath, readmeContent, "utf-8");
      writeFileSync(agentsPath, agentsContent, "utf-8");

      return {
        written: [
          { target: "README.md", path: readmePath },
          { target: "AGENTS.md", path: agentsPath }
        ]
      };
    }
  },
  {
    id: "check",
    title: "Check KB Projections",
    description: "Check if README.md and AGENTS.md are in sync with KB nodes",
    mode: "read" as const,
    aliases: ["project.check", "render.check"],
    inputSchema: passthroughSchema,
    outputSchema: passthroughSchema,
    async handler(ctx: KbContext, _input: unknown) {
      const readmeContent = generateReadme(ctx.nodes);
      const agentsContent = generateAgentsMd(ctx.nodes);

      const readmePath = join(ctx.root, "README.md");
      const agentsPath = join(ctx.root, "AGENTS.md");

      const readmeClean = existsSync(readmePath) && readFileSync(readmePath, "utf-8") === readmeContent;
      const agentsClean = existsSync(agentsPath) && readFileSync(agentsPath, "utf-8") === agentsContent;

      return {
        clean: readmeClean && agentsClean,
        files: [
          { file: "README.md", status: readmeClean ? "clean" : "stale" },
          { file: "AGENTS.md", status: agentsClean ? "clean" : "stale" }
        ]
      };
    }
  }
];
