import { writeFileSync, readFileSync, existsSync } from "node:fs";
import { join } from "node:path";

interface PropValue {
  t: "str" | "num" | "bool" | "date" | "ref";
  v: string | number | boolean;
}

interface KbNode {
  id: string;
  text: string;
  props?: Record<string, PropValue[]>;
  children?: string[];
  createdAt?: string;
  updatedAt?: string;
}

interface KbContext {
  root: string;
  nodes: KbNode[];
  qdb?: unknown;
  store?: unknown;
}

interface PassthroughSchema<T = unknown> {
  parse(val: unknown): T;
}

const passthroughSchema: PassthroughSchema<Record<string, unknown>> = {
  parse(val: unknown): Record<string, unknown> {
    if (val && typeof val === "object" && !Array.isArray(val)) {
      return val as Record<string, unknown>;
    }
    return {};
  }
};

function hasTypeRef(node: KbNode, targetRef: string): boolean {
  const typeProps = node.props?.["sys.f.type"];
  if (!typeProps) return false;
  return typeProps.some((p) => p.t === "ref" && p.v === targetRef);
}

function getPropScalar(node: KbNode, fieldId: string | undefined): string | undefined {
  if (!fieldId || !node.props) return undefined;
  const values = node.props[fieldId];
  if (!values || values.length === 0) return undefined;
  const first = values[0];
  return typeof first.v === "string" ? first.v : String(first.v);
}

function formatSubtree(nodes: KbNode[], rootNode: KbNode, indent = ""): string {
  const lines: string[] = [`${indent}- ${rootNode.text}`];
  if (rootNode.children && Array.isArray(rootNode.children)) {
    for (const childId of rootNode.children) {
      const child = nodes.find((n) => n.id === childId);
      if (child) {
        lines.push(formatSubtree(nodes, child, indent + "  "));
      }
    }
  }
  return lines.join("\n");
}

function getToolingNodes(nodes: KbNode[]): {
  toolNodes: KbNode[];
  fieldMap: Record<string, string>;
} {
  const toolingTag = nodes.find(
    (n) => n.text === "tooling" && hasTypeRef(n, "sys.tag")
  );

  const fieldMap: Record<string, string> = {};
  for (const n of nodes) {
    if (hasTypeRef(n, "sys.field")) {
      fieldMap[n.text] = n.id;
    }
  }

  if (!toolingTag) {
    return { toolNodes: [], fieldMap };
  }

  const toolNodes = nodes.filter((n) => hasTypeRef(n, toolingTag.id));
  return { toolNodes, fieldMap };
}

function renderToolingSection(nodes: KbNode[]): string {
  const { toolNodes, fieldMap } = getToolingNodes(nodes);
  if (toolNodes.length === 0) return "";

  const sections: string[] = [];
  for (const tool of toolNodes) {
    const desc = getPropScalar(tool, fieldMap["description"]);
    const cmd = getPropScalar(tool, fieldMap["command"]);
    const usage = getPropScalar(tool, fieldMap["usage"]);

    const lines: string[] = [`### ${tool.text}`];
    if (desc) lines.push(`- **Description**: ${desc}`);
    if (cmd) lines.push(`- **Command**: \`${cmd}\``);
    if (usage) lines.push(`- **Usage**: \`${usage}\``);

    if (tool.children && tool.children.length > 0) {
      lines.push("- **Details & Workflows**:");
      for (const childId of tool.children) {
        const child = nodes.find((n) => n.id === childId);
        if (child) {
          lines.push(formatSubtree(nodes, child, "  "));
        }
      }
    }
    sections.push(lines.join("\n"));
  }

  return sections.join("\n\n");
}

function getRootContentNodes(nodes: KbNode[]): KbNode[] {
  const { toolNodes } = getToolingNodes(nodes);
  const excludedIds = new Set<string>();

  const collectSubtreeIds = (nodeId: string): void => {
    excludedIds.add(nodeId);
    const node = nodes.find((n) => n.id === nodeId);
    if (node?.children) {
      for (const childId of node.children) {
        collectSubtreeIds(childId);
      }
    }
  };

  for (const tool of toolNodes) {
    collectSubtreeIds(tool.id);
  }

  // Exclude system nodes, tag/field definitions, and tooling subtrees
  const contentNodes = nodes.filter((n) => {
    if (n.id.startsWith("sys.") || n.id.startsWith("lens.")) return false;
    if (hasTypeRef(n, "sys.tag") || hasTypeRef(n, "sys.field")) return false;
    if (excludedIds.has(n.id)) return false;
    return true;
  });

  const childIds = new Set<string>();
  for (const n of contentNodes) {
    if (n.children) {
      for (const c of n.children) childIds.add(c);
    }
  }

  return contentNodes.filter((n) => !childIds.has(n.id));
}

function generateReadme(nodes: KbNode[]): string {
  const rootContentNodes = getRootContentNodes(nodes);
  const principles = rootContentNodes
    .map((n) => formatSubtree(nodes, n))
    .join("\n\n");

  const tooling = renderToolingSection(nodes);

  return `<!-- generated by kb projection; do not edit directly -->
# Learning Workspace

Repo for learning and experiments.

## Principles & Organization
${principles}

## Structure
- Each concept/experiment begins in its own dedicated folder.
- Grouping and hierarchy will evolve as patterns emerge over time.

## Tooling & Knowledge Base
${tooling}
`;
}

function generateAgentsMd(nodes: KbNode[]): string {
  const rootContentNodes = getRootContentNodes(nodes);
  const outline = rootContentNodes
    .map((n) => formatSubtree(nodes, n))
    .join("\n");

  const tooling = renderToolingSection(nodes);

  return `<!-- generated by kb projection; do not edit directly -->
# AGENTS.md

Context and guidelines for AI agents working in this repository.

## Repository Purpose & Rules
- **Learning & Experiments**: This repository is dedicated to learning concepts and running experiments.
- **Starting Simple**: Every concept/experiment starts in its own single directory.
- **Organic Evolution**: Hierarchy and groupings will be introduced only when needed down the line.
- **Attention Marker Style in Examples**: Code examples and demonstrations must use explicit comment markers (\`// ✅ ATTENTION:\`, \`// ⚠️ CRITICAL:\`, \`// ❌ FORBIDDEN:\`, \`// 🔒 COMPILE-TIME:\`) to highlight points of attention, safety rules, and anti-patterns.
## Knowledge Base Summary
${outline}

## Tooling & Workflow Guidelines
${tooling}
`;
}

export default [
  {
    id: "all",
    title: "Project KB to Markdown",
    description: "Render KB outliner nodes into README.md and AGENTS.md",
    mode: "apply" as const,
    aliases: ["project.render", "render.all", "project.all"],
    inputSchema: passthroughSchema,
    outputSchema: passthroughSchema,
    async handler(ctx: KbContext, _input: unknown) {
      const readmeContent = generateReadme(ctx.nodes);
      const agentsContent = generateAgentsMd(ctx.nodes);

      const readmePath = join(ctx.root, "README.md");
      const agentsPath = join(ctx.root, "AGENTS.md");

      writeFileSync(readmePath, readmeContent, "utf-8");
      writeFileSync(agentsPath, agentsContent, "utf-8");

      return {
        written: [
          { target: "README.md", path: readmePath },
          { target: "AGENTS.md", path: agentsPath }
        ]
      };
    }
  },
  {
    id: "check",
    title: "Check KB Projections",
    description: "Check if README.md and AGENTS.md are in sync with KB nodes",
    mode: "read" as const,
    aliases: ["project.check", "render.check"],
    inputSchema: passthroughSchema,
    outputSchema: passthroughSchema,
    async handler(ctx: KbContext, _input: unknown) {
      const readmeContent = generateReadme(ctx.nodes);
      const agentsContent = generateAgentsMd(ctx.nodes);

      const readmePath = join(ctx.root, "README.md");
      const agentsPath = join(ctx.root, "AGENTS.md");

      const readmeClean = existsSync(readmePath) && readFileSync(readmePath, "utf-8") === readmeContent;
      const agentsClean = existsSync(agentsPath) && readFileSync(agentsPath, "utf-8") === agentsContent;

      return {
        clean: readmeClean && agentsClean,
        files: [
          { file: "README.md", status: readmeClean ? "clean" : "stale" },
          { file: "AGENTS.md", status: agentsClean ? "clean" : "stale" }
        ]
      };
    }
  }
];
